config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "photos#index"
  resources :photos
  resources :trashes
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :img
end

app/models/trash.rb
class Trash < ApplicationRecord
  has_one_attached :img
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photo=Photo.all
  end

  def new
    @photo=Photo.new
  end

  def show
    @photo=Photo.find(params[:id])
  end

  def edit
    @photo=Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      redirect_to root_path
    else
      render :new, :status, :unprocessable_entity
    end
  end

  def update
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
      redirect_to @photo
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.each do |pho|
      @url=pho.img 
      @name=pho.name
      @trash=Trash.new(img: @url, name: @name)
    end

    @photo.destroy
    if @photo.destroy(photo_params)
      debugger
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  private
    def photo_params
      params.require(:photo).permit(:name, :img)
    end


end

app/controllers/trashes_controller.rb
class TrashesController < ApplicationController
  def index
    @trash=Trash.all
  end

  def new
    @trash=Trash.new
  end

  def show
    @trash=Trash.find(trash_params)
  end

  def edit
    @trash=Trash.find(params[:id])
  end

  def create
    @trash = Trash.new(trash_params)

    if @trash.save
      redirect_to @trash
    else
      render :new, :status, :unprocessable_entity
  end

  def update
    @trash = Trash.find(params[:id])

    if @trash.update(trash_params)
      redirect_to @trash
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @trash = trash.find(params[:id])
    @trash.each do |tra|
      @url=tra.img 
      @name=tra.name
      @trash=trash.new(img: @url, name: @name)
    end

    @trash.destroy!
  end

  private
  def trash_params
    params.expect(trash: [:img, :name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/trashes_helper.rb
module TrashesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Task Image" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :img, style: "display: block" %>
    <%= form.file_field :img %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :name, "Photos" %>

<h1>Photos</h1>

<div id="photos">
  <% @photo.each do |photo| %>
   <% if photo.img.present?%>
    <%= image_tag photo.img %>
  <%else%>
    <p>No Image</p>
  <%end%>
    <p>
      <%= link_to "Show this photo", photo_path(photo.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<% content_for :name, "New photo" %>

<h1>New Photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>


<%# <%= render @photo %> 

<div>
  <%= link_to "Edit this user", edit_photo_path(@photo) %> |
  <%= link_to "Back to users", photo_path %>

  <%= link_to "Destroy this user", photo_path(@photo.id), turbo_method: :delete %>
</div>